spring.datasource.url=jdbc:postgresql://localhost:5432/hrms_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG

# JWT
jwt.secret=thisIsMySuperSecretKeyForJwtAuthentication123456789012345
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
app.cors.allowed-origin=http://localhost:5173