package com.hrms.security.permission;

public enum Permission {

	// USER
	USER_CREATE, USER_UPDATE, USER_VIEW, USER_VIEW_ALL, USER_DELETE,
	
	USER_ASSIGN_MANAGER,   
    USER_CHANGE_STATUS,

	// ROLE
	ROLE_CHANGE, ROLE_LOG_VIEW,

	// DASHBOARD (ADD THIS)
	DASHBOARD_VIEW, DASHBOARD_ADMIN_VIEW,
	
	ATTENDANCE_CHECK_IN,
	ATTENDANCE_CHECK_OUT,
	ATTENDANCE_VIEW_SELF,
	ATTENDANCE_VIEW_ALL,
	ATTENDANCE_UPDATE,
	ATTENDANCE_MANUAL_CREATE,
	ATTENDANCE_REGULARIZE,
	HOLIDAY_CREATE,
	HOLIDAY_UPDATE,
	HOLIDAY_DELETE,
	HOLIDAY_VIEW,
	SETTINGS_VIEW,
	SETTINGS_UPDATE
}